force-app/main/default/objects/Template_Text__c/Template_Text__c.object-meta.xml
<CustomObject>
    <label>Template Text</label>
    <nameField>
        <label>Prompt Template Text Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_Text__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Template_Text__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Template_Text__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Template_Text__c/fields/Prompt_Text__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Text__c</fullName>
    <label>Prompt Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template_Text__c/fields/Template_Type__c.field-meta.xml
<CustomField>
    <fullName>Template_Type__c</fullName>
    <label>Template Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Copilot Action</fullName>
            </value>
            <value>
                <fullName>Prompt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/home_WorkshopSupport.cls
public with sharing class home_WorkshopSupport {
  @AuraEnabled(cacheable=true)
  public static List<Template_Text__c> getTemplateTextRecords() {
    try {
      return [
        SELECT
          Id,
          Name,
          API_Name__c,
          Label__c,
          Prompt_Text__c,
          Template_Type__c,
          Module__c
        FROM Template_Text__c
        WHERE Module__c != NULL
      ];
    } catch (Exception e) {
      throw new AuraHandledException(
        'Unable to retrieve Template Text Records: ' + e.getMessage()
      );
    }
  }
}