force-app/main/default/objects/Contact/fields/Interests__c.field-meta.xml
<CustomField>
    <fullName>Interests__c</fullName>
    <label>Interests</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Traveler_Profile__c.field-meta.xml
<CustomField>
    <fullName>Traveler_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Traveler Profile</label>
    <referenceTo>Traveler_Profile__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/Itinerary__c.object-meta.xml
<CustomObject>
    <label>Itinerary</label>
    <nameField>
        <displayFormat>ITN-{0000}</displayFormat>
        <label>Itinerary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itineraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Itinerary__c/fields/Accommodation__c.field-meta.xml
<CustomField>
    <fullName>Accommodation__c</fullName>
    <label>Accommodation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Itineraries</relationshipLabel>
    <relationshipName>Itineraries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Transportation__c.field-meta.xml
<CustomField>
    <fullName>Transportation__c</fullName>
    <label>Transportation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravelActivity__c/TravelActivity__c.object-meta.xml
<CustomObject>
    <label>Travel Activity</label>
    <nameField>
        <label>TravelActivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TravelActivity__c/fields/Itinerary__c.field-meta.xml
<CustomField>
    <fullName>Itinerary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Itinerary</label>
    <referenceTo>Itinerary__c</referenceTo>
    <relationshipName>TravelActivities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TravelActivity__c/fields/Outdoor__c.field-meta.xml
<CustomField>
    <fullName>Outdoor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Outdoor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TravelActivity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TravelActivity__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Traveler_Profile__c/Traveler_Profile__c.object-meta.xml
<CustomObject>
    <label>Traveler Profile</label>
    <nameField>
        <label>Traveler Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Traveler Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Traveler_Profile__c/fields/Interests__c.field-meta.xml
<CustomField>
    <fullName>Interests__c</fullName>
    <label>Interests</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Traveler_Profile__c/fields/Special_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Special_Requirements__c</fullName>
    <label>Special Requirements</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/GenerateActivitiesViaSFAPInvocable.cls
global class GenerateActivitiesViaSFAPInvocable {
    @InvocableMethod(label='Generate Trip Itinerary' description='Generate Trip itinerary based on a destination')
    public static List<Itinerary__c> getActivitiesList(List<ApexWithMultipleInput> ids ) {
       // Step 1 Initialize the lists
        List<Itinerary__c> Itinerarylist = new List<Itinerary__c>();
        List<TravelActivity__C> actlist = new List<TravelActivity__c>();
        
        
        //Step 2 : get the json from models api
        String jsonstring=  getJsonFromPrompt(ids[0].destination, ids[0].traveler);
       
        // Step 3: read the json 
        Itinerary itinerary = parseItinerary(jsonString);
             
        // Step 4: insert record
        // Create the Itinerary sObject 
        
        Itinerary__c itin = new Itinerary__c(destination__c=itinerary.destination, contact__c=ids[0].traveler.id,status__c='Planned',start_date__c=itinerary.startdate, end_date__c=itinerary.enddate,accommodation__c=itinerary.accommodation, transportation__c= itinerary.transportation);
        // Insert the account by using DML
        insert itin;
        // Get the new ID on the inserted sObject argument
        ID itinID = itin.Id;
        Itinerarylist.add(itin);
        for (Activity act : itinerary.activities) {
            TravelActivity__c TA = new TravelActivity__c(itinerary__c=itinID, name=act.name,status__c='Planned', outdoor__c=Boolean.valueOf(act.outdoor), date__c=act.localdate,time__c=act.localtime, location__c=act.location );
            actList.add(TA);
        }
        insert actList;
        return Itinerarylist;
    }
    public static String getJsonFromPrompt(String destination, Contact c){
         // Query the TravelerProfile related to the Contact
        // Query the Contact to get the related TravelerProfile
        Contact c1 = [
            SELECT Id, Traveler_Profile__c, Traveler_Profile__r.Interests__c, Traveler_Profile__r.Special_Requirements__c
            FROM Contact
            WHERE Id = :c.Id
            LIMIT 1
        ];
        
 String prompt = 'You are helping a travel agent plan the best itinerary for a traveler\'s upcoming trip to '+ destination+'. The traveler has shared their profile and interests with you. '
  + 'Ensure the itinerary aligns with the traveler\'s preferences and interests as listed here: '
 + c1.Traveler_Profile__r.Interests__c + '. '
  + 'Traveler has special requirements: '
 + c1.Traveler_Profile__r.Special_Requirements__c + '. '
  + 'Based on this information, provide an itinerary that includes accommodation options, must-visit attractions, local experiences, dining recommendations, and transportation activities. Show only three activities. '
  + 'Generate a JSON output with the following structure: '
  + '{"itineraryName": "Paris Trip", '
  + '"destination": "Paris", '
  + '"startDate": "2024-08-20", '
  + '"endDate": "2024-08-21", '
  + '"accommodation": "Paris Boutique Hotel", '
  + '"transportation": "Paris Rails", '
  + '"activities": ['
  + '{"name": "Visit Eiffel Tower", "location": "Eiffel Tower", "localdate": "2024-08-20", "localtime": "09:00", "Outdoor": true}]}';
      
      //Generate the activities via Models API 
     String activity = GenerateActivitiesviaModelsAPI.generateText(prompt);
        //## Sample JSON structure of the activity returned by the abive call
        String samplectivity = '{"itineraryName": "Paris Trip", "destination": "Paris", "startDate": "2024-08-20", "endDate": "2024-08-21", "accommodation": "Paris Boutique Hotel", "transportation": "Paris Rails",'+
            '"activities":[{"name": "Visit Louvre Museum", "location": "Louvre Museum", "localdate": "2024-08-20","localtime": "10:00","outdoor": false},'+
            ' { "name": "Explore Montmartre", "location": "Montmartre",  "localdate": "2024-08-20",  "localtime": "14:00", "outdoor": true},'+
            '{ "name": "Dine at Le Potager du Marais", "location": "Le Potager du Marais", "localdate": "2024-08-20", "localtime": "19:00", "outdoor": false } ]}';            
    
       return activity;  
       //return sampleactivity; 
        
    }
    
    
    
    // Inner classes used for serialization by the parser. 
    
    public class Itinerary {
        public String itineraryName;
        public String destination;
        public Date startDate;
        public Date endDate;
        public String accommodation;
        public String transportation;
        public List<Activity> activities;
        
        public Itinerary(String itineraryName, String status, String dest, Date stdt, Date enddt,String acco, String transport, List<Activity> actList) {
            itineraryName = itineraryName;
            destination = dest;
            startdate = stdt;
            enddate=enddt;
            accommodation = acco;
            transportation = transport; 
            status= status;       
            activities = actList;
        }
    }
    public class Activity {
        public String name;
        public String location;
        public Date localdate;
        public String localtime;
        public Boolean outdoor;
        public String status;
        
        public Activity(String name, String location, Date localdate, String localtime, Boolean outdoor,String status) {
            name = name;
            location = location;
            localdate = localdate;
            localtime=localtime;
            outdoor = outdoor;
            status= status;       
        }
   
  }
    // Method to parse JSON string into an Itinerary object
    public static Itinerary parseItinerary(String jsonStr) {
        
        // Parse JSON string into Itinerary object
        Itinerary itinerary = (Itinerary)JSON.deserialize(jsonStr, Itinerary.class);
        
        return itinerary;
        
    }
   public class ApexWithMultipleInput {
        @InvocableVariable(description='Destination')
        public String destination;
        @invocableVariable(description='Traveler')
        public Contact traveler;
        
    }
}